datadog:
   enabled: true
   api-key: "secretsmanager://dev-template-datadog-api-key"

db:
   url: jdbc:postgresql://hostname:5432/databasename
   username: "secretsmanager://dev-template-rds-username"
   password: "secretsmanager://dev-template-rds-password"
   minimumIdle: 16
   maximumPoolSize: 32
