version: '3.1'

services:
   postgres:
      image: postgres
      restart: always
      environment:
         POSTGRES_USER: sks
         POSTGRES_PASSWORD: letmein
         POSTGRES_DB: mydb
      ports:
         - "5432:5432"
